### ISSUE TITLE
Web - Login Attempt 404s

### ISSUE THREAD

**Issue by hoboken515** [KasperskyLab/klara#10]
Notes
--
- dispatcher running
- worker running
- database up
- web up
- testuser created in users table

Issue
--
- Login attempts seem to go to _**/index.php/login/check**_ which seems incorrect to me.
- This endpoint returns a 404
- Attempts to alter login code to hit _**/login/check**_ still produce 404s

![image](https://user-images.githubusercontent.com/7559464/38443968-3038b510-39b3-11e8-8c3b-9d3b8d6bccd1.png)

**Comment by hoboken515** [comment]
Looks like it was a nginx configuration issue. 
I was previously using this:
```
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }
```

Above wasn't using the php configs for anything not ending in .php
I changed to the below and it began working. 

```
    location ~ \.php.*$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }
```

**Comment by xdanx** [comment]
Yea. I suggest you shouldn't use the `\.php.*$ pattern since it will force the fast-cgi interpreter to try to run **any** file having "php" in the extension. This could lead to problems in other scenarios, such as when users upload some data to your web server, and one user uploading a file called test.php.png embedding PHP code in the PNG file. 

The correct way to set up Nginx and CodeIgniter is outlined here: https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/
